export const GET_RECIPES_STARTED = 'GET_RECIPES_STARTED';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAILED = 'GET_RECIPES_FAILED';
export const CLEAR_RECIPES = 'CLEAR_RECIPES';
export const MARK_RECIPES_END = 'MARK_RECIPES_END';
