export const GET_RECIPES_STARTED = 'GET_RECIPES_STARTED';
export const GET_RECIPES_SUCCESS = 'GET_RECIPES_SUCCESS';
export const GET_RECIPES_FAILED = 'GET_RECIPES_FAILED';
export const CLEAR_RECIPES = 'CLEAR_RECIPES';
export const GET_RECIPE_STARTED = 'GET_RECIPE_STARTED';
export const GET_RECIPE_SUCCESS = 'GET_RECIPE_SUCCESS';
export const GET_RECIPE_FAILED = 'GET_RECIPE_FAILED';
